//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onFit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupa
    {
        public int Id { get; set; }
        public int Id_Szkoly { get; set; }
        public int Id_TypTanca { get; set; }
        public int Id_Poziom { get; set; }
        public Nullable<System.DateTime> Do_Kiedy_Zapisy { get; set; }
        public Nullable<System.DateTime> Poczatek_Zajec { get; set; }
        public bool Czy_Wolne_Miejsca { get; set; }
        public int Id_Dla_Kogo { get; set; }
    
        public virtual Dla_Kogo Dla_Kogo { get; set; }
        public virtual Poziomy Poziomy { get; set; }
        public virtual Szkoly Szkoly { get; set; }
        public virtual Typy_Tanca Typy_Tanca { get; set; }
    }
}
