//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onFit
{
    using System;
    using System.Collections.Generic;
    
    public partial class KartyZajecia
    {
        public int ID { get; set; }
        public int IDZajecia { get; set; }
        public int IDKarty { get; set; }
    
        public virtual Karty Karty { get; set; }
        public virtual Zajecia Zajecia { get; set; }
    }
}
