//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onFit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karty_Szkoly_Intersekcja
    {
        public int Id { get; set; }
        public int Id_Szkoly { get; set; }
        public int Id_Karty { get; set; }
    
        public virtual Typy_Kart Typy_Kart { get; set; }
        public virtual Szkoly Szkoly { get; set; }
    }
}
