//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onFit
{
    using System;
    using System.Collections.Generic;
    
    public partial class KatalogMiejscowosci
    {
        public long ID { get; set; }
        public Nullable<int> Wojewodztwo { get; set; }
        public Nullable<int> Powiat { get; set; }
        public Nullable<int> Gmina { get; set; }
        public Nullable<int> RodzajGminy { get; set; }
        public Nullable<int> RZ { get; set; }
        public Nullable<int> MZ { get; set; }
        public string Nazwa { get; set; }
        public string Symbol { get; set; }
        public string SymbolPod { get; set; }
    }
}
