//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onFit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kiedy_Zajecia
    {
        public int Id { get; set; }
        public int Id_Grupy { get; set; }
        public int Id_Dzien { get; set; }
        public int Godzina_Od { get; set; }
        public int Godzina_Do { get; set; }
    
        public virtual Dni Dni { get; set; }
    }
}
