//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onFit
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Karty> Karty { get; set; }
        public virtual DbSet<KartyZajecia> KartyZajecia { get; set; }
        public virtual DbSet<MiejsceZajec> MiejsceZajec { get; set; }
        public virtual DbSet<NazwaZajec> NazwaZajec { get; set; }
        public virtual DbSet<PoziomyZajec> PoziomyZajec { get; set; }
        public virtual DbSet<Zajecia> Zajecia { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
        public virtual DbSet<TerminyZajec> TerminyZajec { get; set; }
        public virtual DbSet<KatalogMiejscowosci> KatalogMiejscowosci { get; set; }
        public virtual DbSet<KatalogUlic> KatalogUlic { get; set; }
        public virtual DbSet<PodzialAdministracyjny> PodzialAdministracyjny { get; set; }
    
        public virtual ObjectResult<CityFilter_Result> CityFilter(string miejscowosc)
        {
            var miejscowoscParameter = miejscowosc != null ?
                new ObjectParameter("Miejscowosc", miejscowosc) :
                new ObjectParameter("Miejscowosc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CityFilter_Result>("CityFilter", miejscowoscParameter);
        }
    
        public virtual ObjectResult<CityFilter_Result> CityFilter1(string miejscowosc)
        {
            var miejscowoscParameter = miejscowosc != null ?
                new ObjectParameter("Miejscowosc", miejscowosc) :
                new ObjectParameter("Miejscowosc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CityFilter_Result>("CityFilter1", miejscowoscParameter);
        }
    
        public virtual ObjectResult<StreetFilter_Result> StreetFilter(string nazwa, Nullable<int> wojewodztwo, Nullable<int> powiat)
        {
            var nazwaParameter = nazwa != null ?
                new ObjectParameter("Nazwa", nazwa) :
                new ObjectParameter("Nazwa", typeof(string));
    
            var wojewodztwoParameter = wojewodztwo.HasValue ?
                new ObjectParameter("Wojewodztwo", wojewodztwo) :
                new ObjectParameter("Wojewodztwo", typeof(int));
    
            var powiatParameter = powiat.HasValue ?
                new ObjectParameter("Powiat", powiat) :
                new ObjectParameter("Powiat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StreetFilter_Result>("StreetFilter", nazwaParameter, wojewodztwoParameter, powiatParameter);
        }
    
        public virtual ObjectResult<StreetFilter_Result> StreetFilter1(string nazwa, Nullable<int> wojewodztwo, Nullable<int> powiat)
        {
            var nazwaParameter = nazwa != null ?
                new ObjectParameter("Nazwa", nazwa) :
                new ObjectParameter("Nazwa", typeof(string));
    
            var wojewodztwoParameter = wojewodztwo.HasValue ?
                new ObjectParameter("Wojewodztwo", wojewodztwo) :
                new ObjectParameter("Wojewodztwo", typeof(int));
    
            var powiatParameter = powiat.HasValue ?
                new ObjectParameter("Powiat", powiat) :
                new ObjectParameter("Powiat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StreetFilter_Result>("StreetFilter1", nazwaParameter, wojewodztwoParameter, powiatParameter);
        }
    }
}
