//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onFit
{
    using System;
    using System.Collections.Generic;
    
    public partial class PodzialAdministracyjny
    {
        public long ID { get; set; }
        public Nullable<int> Wojewodztwo { get; set; }
        public Nullable<int> Powiat { get; set; }
        public Nullable<int> Gmina { get; set; }
        public Nullable<int> Rodzaj { get; set; }
        public string Nazwa { get; set; }
        public string NazwaDodatkowa { get; set; }
    }
}
