//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onFit
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminyZajec
    {
        public int ID { get; set; }
        public int IDZajec { get; set; }
        public string DzienTygodnia { get; set; }
        public System.TimeSpan GodzinaRozpoczecia { get; set; }
        public System.TimeSpan GodzinaZakonczenia { get; set; }
        public System.DateTime DataRozpoczeciaZajec { get; set; }
    }
}
