//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onFit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zajecia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zajecia()
        {
            this.KartyZajecia = new HashSet<KartyZajecia>();
            this.TerminyZajec = new HashSet<TerminyZajec>();
        }
    
        public int ID { get; set; }
        public int IDMiejsceZajec { get; set; }
        public int IDNazwaZajec { get; set; }
        public int IDPoziomZajec { get; set; }
        public Nullable<int> MaxIloscMiejsc { get; set; }
        public bool CzyWolneMiejsca { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KartyZajecia> KartyZajecia { get; set; }
        public virtual MiejsceZajec MiejsceZajec { get; set; }
        public virtual NazwaZajec NazwaZajec { get; set; }
        public virtual PoziomyZajec PoziomyZajec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TerminyZajec> TerminyZajec { get; set; }
    }
}
